### ISSUE TITLE
Tracking issue for Cairo-rs integration

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#572]
## About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

## Steps

- [x] Integrating Python interpreter for hints execution, with support for mangling globals and locals in execution environment, in order to let us inject cheatcodes.
    - https://github.com/lambdaclass/cleopatra_cairo/issues/334
    - https://github.com/lambdaclass/cairo-rs/pull/413
- [x] Starknet integration.
    - ~There is a chance we can do this by wrapping Cleopatra's `CairoRunner` with Starkware's Python Starknet implementation. To be researched further.~
    - Starkware is planning to work on this internally.
- [x] Bundling Cleopatra in Protostar
    - https://pyo3.rs/
    - https://maturin.rs/
  Currently waiting for https://github.com/lambdaclass/cairo-rs-py to be released, the ETA is 21st OCT
- [ ] Integrate `cairo-rs-py` as alternative VM in Protostar

**Comment by mkaput** [comment]
I have updated issue description to outline topics that we need to investigate.

**Comment by mkaput** [comment]
We are currently waiting for further developments in hints implementation and Starknet work, both are external to us.

**Comment by mkaput** [comment]
@karol-bisztyga is starting work to integrate Cairo-rs in Protostar 🎉

**Comment by karol-bisztyga** [comment]
Issue for cairo-rs support
https://github.com/software-mansion/protostar/issues/1158
Issue for supporting new cairo-lang syntax in cairo-rs
https://github.com/lambdaclass/cairo-rs/issues/620

**Comment by MaksymilianDemitraszek** [comment]
duplicate
